# Generated by Django 4.2.1 on 2023-05-28 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_rename_categoryname_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='owner',
            new_name='influencer',
        ),
    ]
