# Generated by Django 4.2.1 on 2023-05-28 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_rename_owner_listing_influencer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='imageURL',
            field=models.CharField(max_length=1000),
        ),
    ]
