# Generated by Django 4.2.1 on 2023-05-28 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_listing_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='influencer',
            new_name='account',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='title',
            new_name='name',
        ),
    ]
