# Generated by Django 4.2.1 on 2023-05-28 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_rename_influencer_listing_account_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='imageURL',
            new_name='image_url',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='isActive',
            new_name='is_active',
        ),
    ]
