# Generated by Django 4.2.1 on 2023-05-31 13:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_listing_watchlist_alter_listing_posted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='watchlist',
            field=models.ManyToManyField(blank=True, null=True, related_name='watched_listings', to=settings.AUTH_USER_MODEL),
        ),
    ]
