# Generated by Django 4.2.1 on 2023-05-31 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_alter_listing_watchlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='watchlist',
            new_name='watched_by',
        ),
    ]
